### ISSUE TITLE
Insta-crash in 10.14.5

### ISSUE THREAD

**Issue by cannikin** [AkdM/KnightTouchBar2000#15]
I've never tried installing before so this may not be exclusively a 10.14.5 problem...let me know if there's anything else I can do to help troubleshoot!

I have no idea how to parse these crash reports but `Termination Reason:    Namespace CODESIGNING, Code 0x1` stuck out to me.

```Process:               KnightTouchBar2000 [41125]
Path:                  /Applications/KnightTouchBar2000.app/Contents/MacOS/KnightTouchBar2000
Identifier:            com.AnthonyDaMota.KnightTouchBar2000
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KnightTouchBar2000 [41125]
User ID:               501

Date/Time:             2019-08-20 20:07:12.280 -0700
OS Version:            Mac OS X 10.14.5 (18F2058)
Report Version:        12
Bridge OS Version:     3.5 (16P5601)
Anonymous UUID:        F0F99031-34FE-FE8A-0E4C-D489DFB35163

Sleep/Wake UUID:       F2B17B2F-5731-4881-AF94-B6297ED75380

Time Awake Since Boot: 5700 seconds
Time Since Wake:       2400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 0000000100f55000-0000000100f5d000 [   32K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x0000000105685000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffeeecaaba0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000105685000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x100f55000 -        0x100f5cfff + (0) <247B3159-36C6-3833-83BC-D5621A8DBD8C> 
       0x105684000 -        0x1056ee6ef + (655.1.1) <C60D7B63-07FD-3108-A878-67706FE90611> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 77547
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=640K resident=0K(0%) swapped_out_or_unallocated=640K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             240K        3 
__LINKEDIT                         180K        2 
__TEXT                             460K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             64.9M       11 

```

**Comment by wolff000** [comment]
I also get an insta crash and running 10.14.6.  A have a brand new Macbook Pro

Process:               KnightTouchBar2000 [3555]
Path:                  /Volumes/VOLUME/*/KnightTouchBar2000.app/Contents/MacOS/KnightTouchBar2000
Identifier:            com.AnthonyDaMota.KnightTouchBar2000
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           KnightTouchBar2000 [3555]
User ID:               502

Date/Time:             2019-08-27 13:24:21.085 -0400
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Bridge OS Version:     3.6 (16P6571)
Anonymous UUID:        E2C8ED8C-4E4F-C281-0D90-69069624F634

Sleep/Wake UUID:       AEF315CB-D9D6-4580-A376-11872800472D

Time Awake Since Boot: 1800 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    __TEXT                 000000010b796000-000000010b79e000 [   32K] r-x/rwx SM=COW  

Thread 0 Crashed:
0                                 	0x0000000115dc1000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ffee4469ad0
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x0000000115dc1000  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000
Trap Number:     0


Binary Images:
       0x10b796000 -        0x10b79dfff + (0) <247B3159-36C6-3833-83BC-D5621A8DBD8C> 
       0x115dc0000 -        0x115e2a70f + (655.1.1) <DFC3C4AF-6F97-3B34-B18D-7DCB23F2A83A> 

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 265058
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=640K resident=0K(0%) swapped_out_or_unallocated=640K(100%)
Writable regions: Total=8400K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8400K(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                             240K        3 
__LINKEDIT                         180K        2 
__TEXT                             460K        2 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                             64.9M       11 

Model: MacBookPro15,1, BootROM 220.270.99.0.0 (iBridge: 16.16.6571.0.0,0), 6 processors, Intel Core i7, 2.6 GHz, 16 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro555XItem, Radeon Pro 555X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2400 MHz, SK Hynix, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Mar 28 2019 19:17:52 version 9.137.9.0.32.6.34 FWID 01-36f56c94
Bluetooth: Version 6.0.14d3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet Slot 1, Ethernet, en8
Network Service: Wi-Fi, AirPort, en0
PCI Card: pci1b73,1100, USB eXtensible Host Controller, Thunderbolt@196,0,0
PCI Card: ethernet, Ethernet Controller, Thunderbolt@195,0,0
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: USB-C Digital AV Multiport Adapter
USB Device: USB3.0 Hub
USB Device: USB 3.0 Bus
USB Device: USB audio CODEC
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 42.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 42.1
Thunderbolt Device: Thunderbolt 2 Express Dock HD, Belkin International, Inc., 3, 25.1

**Comment by AkdM** [comment]
That's a signing issue. If ever you know how to sign the .app without a paid Apple developer account (and not have this CODESIGNING error after *x* weeks) , let me know.
If you open the project in Xcode and build it yourselves, you will not have the issue.

**Comment by StefanPostma** [comment]
Let others sign you app is not really a solution ;)

**Comment by AkdM** [comment]
Right, however I don't have any other solution atm.

**Comment by mrplug** [comment]
Hey, maybe you should update your README file. :) 

Thank you for this awesome app! :)
